apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: frauddetection-example
spec:
  image: gcr.io/nosidelines/flink-test
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/artifacts/frauddetection-0.1.jar
    parallelism: 2
    upgradeMode: stateless